### ISSUE TITLE
What are the use-cases?

### ISSUE THREAD

**Issue by dlecan** [SpectralOps/keyscope#18]
Hello,

This is a very interesting project, I would like to contribute a new provider: Scaleway

But what are the use-cases if this project?

**Comment by jondot** [comment]
Hi Damien,
Thanks - I'm here to help you with that :)
Right now we're going for validation

PS. The next iteration of keyscope would also be for: invalidation, creation (which will complete a full rotation cycle),  and identification (which will allow to check if a person is OK to have that kind of key + to contact this person if needed).

**Comment by dlecan** [comment]
Thank for the explanations
I think you may improve the « why keyscope » in the readme to attract more users and contributors.
Currently, it is shorter than the « why rust » 😂
