### ISSUE TITLE
Version string out of date

### ISSUE THREAD

**Issue by BoBeR182** [SpectralOps/keyscope#20]
Linux release 1.2.2 shows 1.2.0 release
Is this a string error or the release is not correct version?
![image](https://user-images.githubusercontent.com/525433/191047005-1d4e7608-a91a-471b-ab01-4d4a329ebd7f.png)
![image](https://user-images.githubusercontent.com/525433/191047242-e062eea2-1794-4ce9-93c9-4b28071c6f0f.png)

**Comment by jondot** [comment]
Thanks! looks like fell out of sync.
Would you like to submit a PR? it can be an easy first contribution :) (probably just fix the version in `cargo.toml`)

**Comment by BoBeR182** [comment]
added 1.2.3 to allow for next release tag to match.

**Comment by BoBeR182** [comment]
looks like some devops work needs to be done with the deploy portion of the hooks

**Comment by jondot** [comment]
yep dont worry about it - i'm on it :)
I'll release a new version - thanks!!

**Comment by jondot** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/83390/191824951-051c4dbb-7c35-4f12-a3c3-3db5547d9a31.png">
and we're good!
thanks for all the help, I'm going to go ahead and close this issue 🚀
